import type { Metadata } from 'next';

import { Background } from '~/components/layout/Background';

import '~/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang='en'>
      <body>
        {children}
        <Background />
      </body>
    </html>
  );
}
